# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_auto_20171026_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='manufacturer',
        ),
        migrations.AddField(
            model_name='part',
            name='manufacturers',
            field=models.ManyToManyField(related_name='parts', to='parts.Manufacturer'),
        ),
    ]
