# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0003_auto_20171026_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='manufacturers',
        ),
        migrations.AddField(
            model_name='part',
            name='manufacturer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='parts.Manufacturer'),
            preserve_default=False,
        ),
    ]
