# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 03:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0004_auto_20171026_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subpart',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='parts.Part'),
        ),
        migrations.AlterField(
            model_name='subpart',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='parts.Part'),
        ),
    ]
