# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0005_auto_20171026_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cost',
            name='part',
        ),
        migrations.RemoveField(
            model_name='part',
            name='manufacturer',
        ),
        migrations.AddField(
            model_name='part',
            name='desc',
            field=models.TextField(default='Initial items no desc'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Cost',
        ),
        migrations.DeleteModel(
            name='Manufacturer',
        ),
    ]
